name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose --profile "*" up -d

      - name: Wait for Services to Start
        run: sleep 10 # Give time for services to be ready

      - name: Run Tests
        run: |
          docker exec flask_app pytest -vs tests/test_app.py

      - name: Stop Docker Containers
        run: docker compose down
